coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "header, diff, files, components"

component_management:
  individual_components:
    # StudioCMS UI
    - component_id: studiocms_ui
      name: "@studiocms/ui"
      paths:
        - packages/studiocms_ui/**