packages:
  - packages/*
  - packages/*/test/fixtures/*
  - docs

catalog:
  "@astrojs/check": ^0.9.7
  "@fontsource-variable/onest": 5.1.0
  "@iconify-json/heroicons": ^1.2.1
  "@types/node": ^24.12.0
  astro: ^6.0.0
  typescript: ^5.9.3

catalogs:
  peers:
    astro: ^4.5 || ^5.0.0-beta.0 || ^6.0.0-beta.20
    vite: ^5.0.0 || ^6.0.0 || ^7.0.0

minimumReleaseAgeExclude:
  - studiocms
  - "@studiocms/*"
  - "@withstudiocms/*"

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - esbuild
  - sharp
