name: CI - Push main

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-main
  cancel-in-progress: true

permissions: {}

jobs:
  format:
    name: Format
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    secrets: inherit
    uses: withstudiocms/automations/.github/workflows/format.yml@f32588d80ce35d57905264f7fa473b0f6e297c0a # main

  todo:
    name: TODOs
    permissions:
      contents: write
      issues: write
    secrets: inherit
    uses: withstudiocms/automations/.github/workflows/todo.yml@f32588d80ce35d57905264f7fa473b0f6e297c0a # main

  release:
    name: Release
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    secrets: inherit
    uses: withstudiocms/automations/.github/workflows/release.yml@f32588d80ce35d57905264f7fa473b0f6e297c0a # main
    with:
      build-cmd: "pnpm ci:build"
      RoleMentionId: '1309310416362537020'

  mergebot:
    name: CI - Merge Bot
    if: github.repository_owner == 'withstudiocms' && github.event.head_commit.message != '[ci] lint'
    uses: withstudiocms/automations/.github/workflows/mergebot.yml@f32588d80ce35d57905264f7fa473b0f6e297c0a # main
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_MERGEBOT }}

  preview-main:
    name: Continuous Deployment Snapshot
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
    secrets: inherit
    uses: withstudiocms/automations/.github/workflows/preview.yml@f32588d80ce35d57905264f7fa473b0f6e297c0a # main
    with:
      build-cmd: "pnpm ci:build"