name: CI - Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-testing-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  
jobs:
  codecov:
    name: Run Tests & Code Coverage
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - name: Check out code using Git
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
  
      - name: Install Tools & Dependencies
        uses: withstudiocms/automations/.github/actions/install@885437ef4376e64fc295161092b8a165bc5efd39 # main

      - name: Build packages
        run: pnpm ci:build

      - name: Run Tests & Code Coverage
        run: pnpm ci:test
        continue-on-error: ${{ github.event_name == 'pull_request' }}

      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          slug: withstudiocms/ui
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ always() }}
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f
        with:
          slug: withstudiocms/ui
          token: ${{ secrets.CODECOV_TOKEN }}